services:
  base:
    init: true
    restart: unless-stopped
    image: xtrime/antizapret-vpn-wireguard:6.1.0@sha256:5f1bf799468e14fd59bd1dae4a7fab288a199e325dcb087069aeb9bb7064b1f3
    build:
      context: .
      args:
        - IMAGE=ghcr.io/wg-easy/wg-easy:15
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
    healthcheck:
      test: (/healthcheck.sh || kill -TERM 1) 2>&1 | tee /proc/1/fd/1
      interval: 5s
      timeout: 1s
      start_period: 5s
      start_interval: 1s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    depends_on:
      - az-local
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config/antizapret/result:/opt/antizapret/result
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [ node.labels.location == local ]
    environment:
      - PORT=51821
      - INSECURE=true
      - DISABLE_IPV6=true
      - WG_PORT=51820
      - WG_DEFAULT_DNS=14.16.0.1
      - AZ_SUBNET=14.16.0.0/14
      - WG_PERSISTENT_KEEPALIVE=25
      - |
        ROUTES=
        openvpn:10.1.165.0/24;
        wireguard:10.1.166.0/24;
        wireguard-amnezia:10.1.167.0/24;
        adguard:14.16.0.1;
        az-local:14.16.0.0/15;
        az-world:14.18.0.0/15;
