services:
  wireguard:
    extends:
      file: docker-compose.base.yml
      service: base
    hostname: wireguard.antizapret
    ports:
      - "51820:51820/udp"
    environment:
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.1.166.x
    volumes:
      - $PWD/config/wireguard:/etc/wireguard

  wireguard-amnezia:
    extends:
      file: docker-compose.base.yml
      service: base
    hostname: wireguard-amnezia.antizapret
    ports:
      - "51830:51830/udp"
    environment:
      - WG_PORT=51830
      - WG_DEFAULT_ADDRESS=10.1.167.x
      - EXPERIMENTAL_AWG=true
      - OVERRIDE_AUTO_AWG=awg
      - JC=3
      - JMIN=20
      - JMAX=100
      - I1=<r 2><b 0x8580000100010000000004796162730679616e6465780272750000010001c00c000100010000026d000457fa27d1>
    volumes:
      - $PWD/config/wireguard_amnezia:/etc/wireguard
