services:
  ipsec:
    image: hwdsl2/ipsec-vpn-server:debian
    restart: unless-stopped
    hostname: ipsec
    environment:
      - VPN_L2TP_NET=10.1.163.0/24
      - VPN_L2TP_LOCAL=10.1.163.1
      - VPN_L2TP_POOL=10.1.163.10-10.1.163.254
      - VPN_XAUTH_NET=10.1.162.0/24
      - VPN_XAUTH_POOL=10.1.162.10-10.1.162.254
      - VPN_DNS_SRV1=10.224.0.1
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    volumes:
      - ./ipsec/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "2"
    depends_on:
      - antizapret
