services:
  wireguard-amnezia:
    image: ghcr.io/w0rng/amnezia-wg-easy
    volumes:
      - ./config/wireguard_amnezia:/etc/wireguard
    devices:
      - /dev/net/tun:/dev/net/tun
    extends:
      file: docker-compose.wireguard.yml
      service: wireguard
