services:
  openvpn:
    image: xtrime/openvpn
    build:
      context: .
      dockerfile: Dockerfile-openvpn
    environment:
      - AUTO_INITIAL=1 # Auto initial (clean to install via wizard)
      - OPENVPN_ADMIN_USERNAME=admin
      - SITE_NAME # Title web ui
      - OPENVPN_PORT # Port openvpn server, default 1194
      - OPENVPN_LOCAL_IP_RANGE # IP range for OpenVPN, default 10.1.165.0
      - OPENVPN_PROTOCOL # Set protocol 1 - udp or 2 - tcp, default: 1
      - URL_PREFIX # URL prefix to admin ui, example: /admin-openvpn
      - APP_PORT=1195 # Set web ui port
    env_file:
      - ./openvpn/.env
    ports:
      - "1195:1195/tcp" # For web ui
      - "1194:1194/udp" # For OpenVPN
      - "1194:1194/tcp" # For OpenVPN
    restart: unless-stopped
    privileged: true
    stop_signal: SIGRTMIN+4
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn/scripts:/opt/scripts
      - ./config/openvpn/conf:/etc/openvpn
      - ./config/openvpn/db:/opt/openvpn-gui/db
      - ./config/antizapret/result:/opt/antizapret/result
    healthcheck:
      test: cmp /etc/openvpn/openvpn-blocked-ranges.txt /opt/antizapret/result/openvpn-blocked-ranges.txt || sh -c 'kill -INT -1 && (sleep 5; kill -s 9 -1)'
      interval: 60s                         
      timeout: 30s
      retries: 1
    depends_on:
      - antizapret-vpn
