services:
  openvpn:
    build:
      context: ./
      dockerfile: Dockerfile-openvpn
    privileged: true
    ports:
      - "1194:1194/udp"   # openvpn UDP port
      # - "1194:1194/tcp"   # openvpn TCP port
    environment:
      - OBFUSCATE_TYPE=0
    volumes:
      - ./config/openvpn:/etc/openvpn
      - ./openvpn/easy-rsa.vars:/etc/openvpn/config/easy-rsa.vars
      - ./openvpn/fw-rules.sh:/opt/app/fw-rules.sh
      - ./openvpn/checkpsw.sh:/opt/app/checkpsw.sh
      - ./config/antizapret/result:/opt/antizapret/result
    healthcheck:
      test: cmp /etc/openvpn/openvpn-blocked-ranges.txt /opt/antizapret/result/openvpn-blocked-ranges.txt || sh -c 'killall -INT -r openvpn && (sleep 5; killall -s 9 -r openvpn)'
      interval: 30s
      timeout: 10s
      retries: 1
    restart: unless-stopped
    depends_on:
      - "openvpn-ui"
  openvpn-ui:
    build:
      context: ./
      dockerfile: Dockerfile-openvpn-ui
    environment:
      - OPENVPN_ADMIN_USERNAME=admin
      - OPENVPN_ADMIN_PASSWORD=gagaZush
    privileged: true
    volumes:
      - ./openvpn/easy-rsa.vars:/usr/share/easy-rsa/var
      - ./openvpn/init.db:/opt/openvpn-ui/init.db
      - ./config/openvpn/db:/opt/openvpn-ui/db
      - ./config/openvpn/pki:/usr/share/easy-rsa/pki
      - ./config/openvpn:/etc/openvpn
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped