services:
  adguard:
    environment:
      - ADGUARDHOME_USERNAME=admin
      - ADGUARDHOME_PASSWORD=password

  https:
    environment:
      # If not set, will be created and used self-signed certificate
      - PROXY_DOMAIN=
      # If not set, will be created and used self-signed certificate
      - PROXY_EMAIL=

  # cloak:
  #   extends:
  #     file: services/cloak/docker-compose.yml
  #     service: cloak

  dashboard:
    extends:
      file: services/dashboard/docker-compose.yml
      service: dashboard
    environment:
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=password

  filebrowser:
    extends:
      file: services/filebrowser/docker-compose.yml
      service: filebrowser
    environment:
      - FILEBROWSER_USERNAME=admin
      - FILEBROWSER_PASSWORD=password

  openvpn:
    extends:
      file: services/openvpn/docker-compose.yml
      service: openvpn
    depends_on:
      - openvpn-ui

  openvpn-ui:
    extends:
      file: services/openvpn/docker-compose.yml
      service: openvpn-ui
    environment:
      - OPENVPN_ADMIN_PASSWORD=password

  wireguard:
     extends:
       file: services/wireguard/docker-compose.yml
       service: wireguard
     environment:
       - WIREGUARD_PASSWORD=password

  wireguard-amnezia:
    extends:
      file: services/wireguard/docker-compose.yml
      service: wireguard-amnezia
    environment:
      - WIREGUARD_PASSWORD=password

  socks-local:
    hostname: socks-local.antizapret
    extends:
      file: services/socks/compose.yml
      service: socks
    environment:
      # Omit SOCKS_USERNAME and SOCKS_PASSWORD to disable authentication
      - SOCKS_USERNAME=admin
      - SOCKS_PASSWORD=password
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [ node.labels.location == local ]

  socks-world:
    hostname: socks-world.antizapret
    extends:
      file: services/socks/compose.yml
      service: socks
    environment:
      # Omit SOCKS_USERNAME and SOCKS_PASSWORD to disable authentication
      - SOCKS_USERNAME=admin
      - SOCKS_PASSWORD=password
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [ node.labels.location == world ]
