FROM d3vilh/openvpn-ui

RUN apk update && apk upgrade --no-cache && apk add --no-cache --upgrade grep moreutils sqlite

ADD ./openvpn/ui-start.sh /opt/start.sh
ADD ./openvpn/restart.sh /opt/scripts/restart.sh