services:
  http-proxy:
    image: xtrime/antizapret-vpn-http-proxy:6.0.0
    init: true
    build:
      context: .
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - HTTP_PROXY_USERNAME
      - HTTP_PROXY_PASSWORD
      - HTTP_PROXY_PORT
      - HTTPS_PROXY_PORT
      - |
        ROUTES=
        openvpn:10.1.165.0/24;
        wireguard:10.1.166.0/24;
        wireguard-amnezia:10.1.167.0/24;
        adguard:14.16.0.1;
        az-local:14.16.0.0/15;
        az-world:14.18.0.0/15;
