#!/bin/bash
# Some protection
set -Eeuo pipefail
shopt -s nullglob

FLAG_FILE="/tmp/.ocserv_started"
rm -f "$FLAG_FILE"

# Define default server vars if they are not set
export OCSERV_DIR="/etc/ocserv"
. /certificate.sh
CERT_WAIT_TIMEOUT="${CERT_WAIT_TIMEOUT:-180}"
OC_DEFAULT_ADDRESS="${OC_DEFAULT_ADDRESS:-10.1.164.x}"
export OC_PORT="${OC_PORT:-443}"
OC_USER="${OC_USER:-admin}"
OC_USERPASS="${OC_USERPASS:-pASSword}"
if [[ ! "$OC_DEFAULT_ADDRESS" =~ ^([0-9]{1,3}\.){3}x$ ]]; then
    echo "Invalid OC_DEFAULT_ADDRESS: $OC_DEFAULT_ADDRESS. Expected an IPv4 template ending in .x" >&2
    exit 1
fi
IFS=. read -r octet1 octet2 octet3 _ <<< "$OC_DEFAULT_ADDRESS"
for octet in "$octet1" "$octet2" "$octet3"; do
    if ((10#$octet > 255)); then
        echo "Invalid OC_DEFAULT_ADDRESS: $OC_DEFAULT_ADDRESS" >&2
        exit 1
    fi
done
export OC_IPV4_CIDR="${OC_DEFAULT_ADDRESS%.x}.0/24"
export OC_SECRET="${OC_SECRET:-kvn}"
OCSERV_TEMPLATE="${OCSERV_DIR}/ocserv.tmpl"
ROUTE_TEMPLATE="${OCSERV_DIR}/az.tmpl"
RUNTIME_DIR="/run/ocserv"
export OC_ROUTE="${RUNTIME_DIR}/config-per-group"
RUNTIME_CONFIG="${RUNTIME_DIR}/ocserv.conf"
CONFIG_FILES=(/opt/antizapret/result/ips*)

wait_for_certificate() {
    local elapsed=0

    while ! find_https_certificate \
        || [[ ! -s "$CERT_IDENTITY_FILE" || ! -s "$CERT_TYPE_FILE" ]]; do
        if ((elapsed >= CERT_WAIT_TIMEOUT)); then
            echo "HTTPS certificate was not generated within ${CERT_WAIT_TIMEOUT}s" >&2
            return 1
        fi
        sleep 1
        ((elapsed += 1))
    done
}

config_checksum() {
    if ((${#CONFIG_FILES[@]})); then
        cat "${CONFIG_FILES[@]}"
    fi | md5sum | cut -d' ' -f1
}

# Read the certificate identity generated by the HTTPS service.
wait_for_certificate
CERT_IDENTITY=$(<"$CERT_IDENTITY_FILE")
CERT_TYPE=$(<"$CERT_TYPE_FILE")
case "$CERT_TYPE" in
    dns)
        export OC_DEFAULT_DOMAIN="default-domain = $CERT_IDENTITY"
        ;;
    ip)
        export OC_DEFAULT_DOMAIN=""
        ;;
    *)
        echo "Unsupported HTTPS certificate identity type: $CERT_TYPE" >&2
        exit 1
        ;;
esac

mkdir -p "$OC_ROUTE"
# Create old sample.config
if [[ -r /usr/share/doc/ocserv/sample.config && ! -e "$OCSERV_DIR/sample.config" ]]; then
    cp /usr/share/doc/ocserv/sample.config "$OCSERV_DIR/"
fi

# Create ocserv config files
if [[ ! -e "$OCSERV_TEMPLATE" ]]; then
    cp /ocserv.tmpl "$OCSERV_TEMPLATE"
fi
if [[ ! -e "$ROUTE_TEMPLATE" ]]; then
    cp /az.tmpl "$ROUTE_TEMPLATE"
fi
envsubst < "$OCSERV_TEMPLATE" > "$RUNTIME_CONFIG"
# oc routes
envsubst < "$ROUTE_TEMPLATE" > "$OC_ROUTE/az"
if ((${#CONFIG_FILES[@]})); then
    sort -Vu "${CONFIG_FILES[@]}" | sed 's_.*_route = &_' >> "$OC_ROUTE/az"
fi


printf 'Generated ocserv config (%s):\n' "$RUNTIME_CONFIG"
sed -E 's|^([[:space:]]*camouflage_secret[[:space:]]*=[[:space:]]*).*$|\1"***"|' "$RUNTIME_CONFIG"
printf 'Generated ocserv group config (%s):\n' "$OC_ROUTE/az"
cat "$OC_ROUTE/az"
echo "***** Generated config end *****"

# add user
if [[ ! -e "$OCSERV_DIR/ocpasswd" ]]; then
    printf '%s\n%s\n' "$OC_USERPASS" "$OC_USERPASS" |
        ocpasswd -g az -c "$OCSERV_DIR/ocpasswd" "$OC_USER"
fi


routes --vpn &

config_checksum > /.config_md5
certificate_checksum > /.certificate_state_md5

# Configure network
mkdir -p /dev/net
if [ ! -c /dev/net/tun ]; then
    mknod /dev/net/tun c 10 200
fi

echo "Starting OpenConnect Server"
touch "$FLAG_FILE"
exec "$@"
