#!/bin/bash
# Some protection
set -Eeuo pipefail
shopt -s nullglob

FLAG_FILE="/tmp/.ocserv_started"
rm -f "$FLAG_FILE"

# Define default server vars if they are not set
export OCSERV_DIR="/etc/ocserv"
. /certificate.sh
CERT_WAIT_TIMEOUT="${CERT_WAIT_TIMEOUT:-180}"
OC_DEFAULT_ADDRESS="${OC_DEFAULT_ADDRESS:-10.1.164.x}"
export OC_PORT="${OC_PORT:-443}"
OC_USER="${OC_USER:-admin}"
OC_USERPASS="${OC_USERPASS:-pASSword}"
export OC_IPV4_CIDR="${OC_DEFAULT_ADDRESS/x/0}/24"
export OC_SECRET="${OC_SECRET:-kvn}"
OC_ROUTE="${OCSERV_DIR}/config-per-group"
CONFIG_FILES=(/opt/antizapret/result/ips*)

wait_for_certificate() {
    local elapsed=0

    while ! find_https_certificate \
        || [[ ! -s "$CERT_IDENTITY_FILE" || ! -s "$CERT_TYPE_FILE" ]]; do
        if ((elapsed >= CERT_WAIT_TIMEOUT)); then
            echo "HTTPS certificate was not generated within ${CERT_WAIT_TIMEOUT}s" >&2
            return 1
        fi
        sleep 1
        ((elapsed += 1))
    done
}

config_checksum() {
    if ((${#CONFIG_FILES[@]})); then
        cat "${CONFIG_FILES[@]}"
    fi | md5sum | cut -d' ' -f1
}

# Read the certificate identity generated by the HTTPS service.
wait_for_certificate
CERT_IDENTITY=$(<"$CERT_IDENTITY_FILE")
CERT_TYPE=$(<"$CERT_TYPE_FILE")
case "$CERT_TYPE" in
    dns)
        export OC_DEFAULT_DOMAIN="default-domain = $CERT_IDENTITY"
        ;;
    ip)
        export OC_DEFAULT_DOMAIN=""
        ;;
    *)
        echo "Unsupported HTTPS certificate identity type: $CERT_TYPE" >&2
        exit 1
        ;;
esac

# Create config dirs
for sub_dir in "$OC_ROUTE"; do
    if [[ ! -d "$sub_dir" ]]; then
        mkdir -p "$sub_dir"
    fi
done
# Create old sample.config
if [[ -r /usr/share/doc/ocserv/sample.config && ! -e "$OCSERV_DIR/sample.config" ]]; then
    cp /usr/share/doc/ocserv/sample.config "$OCSERV_DIR/"
fi

# Create ocserv config files
envsubst < /ocserv.tmpl > "$OCSERV_DIR/ocserv.conf"
envsubst < /az.tmpl > "$OC_ROUTE/az.0"
# oc routes
cp -f "$OC_ROUTE/az.0" "$OC_ROUTE/az"
if ((${#CONFIG_FILES[@]})); then
    sort -Vu "${CONFIG_FILES[@]}" | sed 's_.*_route = &_' >> "$OC_ROUTE/az"
fi

# add user
if [[ ! -e "$OCSERV_DIR/ocpasswd" ]]; then
    printf '%s\n%s\n' "$OC_USERPASS" "$OC_USERPASS" |
        ocpasswd -g az -c "$OCSERV_DIR/ocpasswd" "$OC_USER"
fi


routes --vpn &

config_checksum > /.config_md5
printf '%s\n' "$CERT_IDENTITY" > /.certificate_identity
md5sum "$SERVER_CERT" | cut -d' ' -f1 > /.certificate_md5

# Configure network
mkdir -p /dev/net
if [ ! -c /dev/net/tun ]; then
    mknod /dev/net/tun c 10 200
fi

echo "Starting OpenConnect Server"
touch "$FLAG_FILE"
exec "$@"
