services:
  coredns:
    image: xtrime/antizapret-vpn-coredns:6.2.0
    hostname: coredns.antizapret
    restart: unless-stopped
    init: true
    build: 
      context: .
      args:
        - COREDNS_VERSION=v1.14.2
        - FINALIZER_COMMIT=58ec3004e1eae73ccc0289f4067faabe8ebb77cc
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: (/root/healthcheck.sh || kill -TERM 1) 2>&1 | tee /proc/1/fd/1
      interval: 10s
      timeout: 1m
      start_period: 5s
      start_interval: 1s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [ node.labels.location == local ]
    depends_on:
      - az-local
      - az-world
